yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
    "styled-components@*":
        dependencies:
            babel-plugin-macros: "*"
    "react-scripts@*":
        peerDependencies:
            react: "*"
    "follow-redirects@*":
        dependencies:
            debug: "*"
    "ws@*":
        dependencies:
            bufferutil: "*"
            utf-8-validate: "*"
